"""Initial migration

Revision ID: 1c0711c76e44
Revises: 
Create Date: 2025-01-03 13:44:50.684179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0711c76e44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiosk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location_text', sa.String(length=200), nullable=True),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_connection', sa.DateTime(), nullable=True),
    sa.Column('last_action_state', sa.String(length=50), nullable=True),
    sa.Column('sensors_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kiosk')
    # ### end Alembic commands ###
