"""Add State, Action and KioskLog models

Revision ID: fb8edc3d3829
Revises: 1c0711c76e44
Create Date: 2025-01-03 13:48:44.383488

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb8edc3d3829'
down_revision = '1c0711c76e44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kiosk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kiosk',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('location_text', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_connection', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_action_state', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('sensors_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='kiosk_pkey'),
    sa.UniqueConstraint('serial_number', name='kiosk_serial_number_key')
    )
    # ### end Alembic commands ###
